/*
 * Which bracketed runs are tags and which are literal text, pinned against
 * Python Rich.
 *
 * [LAW:one-source-of-truth] `markup-grammar.golden.txt` is a committed copy of
 * the reference implementation's own output, not of this port's. The tag
 * grammar is the one decision in the library that can delete a user's text
 * without any error or visual trace: a run the parser accepts as an opening tag
 * has its brackets and its name removed, and if the name resolves to no style
 * the whole thing simply vanishes. `Console.print` sends every string through
 * it, so the blast radius is the entire library. A golden generated by running
 * this port could only notice that the grammar changed, never that it was
 * wrong. It was wrong: `TAG_RE` carried a hand-written character class that had
 * drifted from `RE_TAGS` in both directions at once, so `[INFO] starting up`
 * printed as ` starting up` while `[a+b]plus` stayed literal where the
 * reference styles it (rich-markup-sec).
 *
 * Regenerating it therefore means re-deriving it from the reference, never from
 * this library — accepting whatever this library currently prints would launder
 * a regression into the fixture and destroy the only thing it is for. Python
 * Rich is not installable from here (pypi is TLS-intercepted) but GitHub is,
 * and it runs from a bare checkout. This is the command the committed fixture
 * came out of, verified to reproduce it byte for byte; run it from the
 * repository root:
 *
 *     git clone --depth 1 https://github.com/Textualize/rich.git /tmp/rich-src
 *     PYTHONPATH=/tmp/rich-src python3 - > test/core/markup-grammar.golden.txt <<'PY'
 *     import io, sys
 *     from rich.console import Console
 *     from rich.markup import MarkupError
 *     CASES = [
 *         ("upper", "[INFO] starting up"),
 *         ("upper-close", "[UPPER]x[/UPPER]"),
 *         ("lower", "[red]hi[/red]"),
 *         ("hash", "[#ff0000]hi[/]"),
 *         ("at", "[@click]hi[/]"),
 *         ("digit", "[1] numbered"),
 *         ("space", "[ red]leading space"),
 *         ("non-ascii", "[\u043a\u0440\u0430\u0441\u043d\u044b\u0439]cyrillic"),
 *         ("empty", "[]empty"),
 *         ("punct-plus", "[a+b]plus[/a+b]"),
 *         ("punct-paren", "[a(b)]paren"),
 *         ("punct-comma", "[a,b]comma"),
 *         ("inner-slash", "[a/b]slash"),
 *         ("tab", "[a\tb]tab"),
 *         ("nested-open", "[a[b]nested open"),
 *         ("implicit", "[red]a[/]b"),
 *         ("implicit-space", "[red]a[/ ]b"),
 *         ("close-trailing-space", "[/red ]x"),
 *         ("orphan-close", "[/] alone"),
 *         ("kv", "[a=1 b=2]kv[/]"),
 *         ("escaped", "\\[red]escaped"),
 *         ("mixed", "text [INFO] more [red]x[/red]"),
 *         ("nested-styles", "[bold]a[italic]b[/italic]c[/bold]"),
 *     ]
 *     def esc(s):
 *         return (s.replace("\\", "\\\\").replace("\x1b", "\\e")
 *                  .replace("\n", "\\n").replace("\t", "\\t"))
 *     blocks = []
 *     for name, markup in CASES:
 *         console = Console(file=io.StringIO(), force_terminal=True,
 *                           color_system="truecolor", width=80, highlight=False)
 *         try:
 *             console.print(markup)
 *             out = esc(console.file.getvalue().rstrip("\n"))
 *         except MarkupError:
 *             out = "<MarkupError>"
 *         blocks.append("%s\nin  %s\nout %s" % (name, esc(markup), out))
 *     sys.stdout.write("\n\n".join(blocks) + "\n")
 *     PY
 *
 * It goes end to end through `Console.print` with colour forced on, rather than
 * comparing the `Span` lists `markup.render` returns, and the difference is not
 * cosmetic. The reference keeps an unresolvable style name on the span as a
 * string and discards it later; this port maps it to the null style at
 * `RichText`'s own boundary. Both print the same bytes — `console.print("[a]b[/a]")`
 * is `b` on either side — so a span-level fixture would report a divergence that
 * no user can observe, and would have to be excused case by case until it
 * excused the real ones too. The bytes are the contract; the spans are how each
 * side happens to reach it.
 *
 * `highlight=False` is load-bearing on both sides: the default `ReprHighlighter`
 * styles bare numbers and URLs, which would paint half this corpus with colour
 * that has nothing to do with markup.
 *
 * WHY THIS CORPUS. Every case buys one arm of `RE_TAGS` that no other buys, and
 * the grammar is two questions — which character may *open* a tag, and what the
 * body may then contain.
 *
 * Opening: `lower`, `hash` and `at` are the three accepted classes (`a-z`, `#`,
 * `@`); `at` in particular is a whole class this port used to reject. `upper`
 * is the ticket's own symptom and the reason the file exists. `upper-close` is
 * its complement and the sharper of the pair: `[UPPER]` is literal while
 * `[/UPPER]` in the same string is a real closing tag, which is only true if the
 * class is tested against the *first* character and `/` belongs to it — a
 * grammar that merely lowercased the input would pass `upper` and fail here.
 * `digit`, `space`, `empty` and `non-ascii` are the rejected classes;
 * `non-ascii` is there because `a-z` is an ASCII range and a lowercase Cyrillic
 * word is exactly what a Unicode-aware rewrite would silently start eating.
 *
 * Body: the reference admits everything except `[`, where this port used to
 * enumerate. `punct-plus`, `punct-paren`, `punct-comma`, `inner-slash` and `tab`
 * are five characters that enumeration omitted, and `inner-slash` doubles as
 * proof that `/` is only special in first position. `nested-open` is the single
 * excluded character, and it also pins where the match starts: the tag is the
 * inner `[b]`, so `[a` survives as literal text.
 *
 * Closing: `implicit` and `implicit-space` separate the two spellings of "close
 * whatever is open" — the reference strips the name before asking whether one
 * is left, so `[/ ]` is an implicit close and not an explicit close of the empty
 * style. `close-trailing-space` is the other side of that strip: a name *does*
 * survive, so it is an explicit close, and it matches nothing. `orphan-close` is
 * the degenerate error arm.
 *
 * The rest are compounds. `kv` carries `=` parameters, `escaped` a backslash
 * that suppresses a tag, and `mixed` puts a literal bracketed word and a real
 * tag in one string, which is the shape a log line actually has.
 *
 * `nested-styles` nests two *attributes* rather than two colours, and that is a
 * constraint the fixture is under rather than a preference: this port disagrees
 * with the reference on both of the other nestings, and a golden that mixed the
 * two provenances would be worth nothing. Both disagreements are pinned as
 * their own checks below.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { Console } from "../../src/core/console.js";
import { MarkupError } from "../../src/core/markup.js";

const GOLDEN = new URL("./markup-grammar.golden.txt", import.meta.url);

const CASES: readonly (readonly [string, string])[] = [
  ["upper", "[INFO] starting up"],
  ["upper-close", "[UPPER]x[/UPPER]"],
  ["lower", "[red]hi[/red]"],
  ["hash", "[#ff0000]hi[/]"],
  ["at", "[@click]hi[/]"],
  ["digit", "[1] numbered"],
  ["space", "[ red]leading space"],
  ["non-ascii", "[красный]cyrillic"],
  ["empty", "[]empty"],
  ["punct-plus", "[a+b]plus[/a+b]"],
  ["punct-paren", "[a(b)]paren"],
  ["punct-comma", "[a,b]comma"],
  ["inner-slash", "[a/b]slash"],
  ["tab", "[a\tb]tab"],
  ["nested-open", "[a[b]nested open"],
  ["implicit", "[red]a[/]b"],
  ["implicit-space", "[red]a[/ ]b"],
  ["close-trailing-space", "[/red ]x"],
  ["orphan-close", "[/] alone"],
  ["kv", "[a=1 b=2]kv[/]"],
  ["escaped", "\\[red]escaped"],
  ["mixed", "text [INFO] more [red]x[/red]"],
  ["nested-styles", "[bold]a[italic]b[/italic]c[/bold]"],
];

function esc(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\x1b/g, "\\e")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

/** What `Console.print` puts on the wire for one markup string, colour forced on. */
function printed(markup: string): string {
  const chunks: string[] = [];
  const console_ = new Console({
    file: { write: (chunk) => chunks.push(String(chunk)) },
    forceTerminal: true,
    colorSystem: "truecolor",
    width: 80,
    highlight: false,
  });
  console_.print(markup);
  return chunks.join("").replace(/\n+$/, "");
}

describe("markup tag grammar", () => {
  it("takes the same bracketed runs as tags that Python Rich takes", () => {
    const rendered =
      CASES.map(([name, markup]) => {
        let out: string;
        try {
          out = esc(printed(markup));
        } catch (err) {
          if (!(err instanceof MarkupError)) throw err;
          out = "<MarkupError>";
        }
        return `${name}\nin  ${esc(markup)}\nout ${out}`;
      }).join("\n\n") + "\n";

    expect(rendered).toBe(readFileSync(GOLDEN, "utf8"));
  });

  /*
   * Nesting one colour inside another is the first of the two nestings the
   * fixture above cannot hold.
   *
   * `markup.render` closes a tag by pushing its span, so the spans come out in
   * the order their tags *closed* — innermost first — and are then applied to
   * the `RichText` in that order. The outer span is applied last and covers the
   * inner one. Rich sorts by `start` before assigning (`sorted(spans[::-1],
   * key=attrgetter("start"))`), which puts the outer span down first and lets
   * the inner override it.
   *
   * Two overlapping attributes hide it, because attributes accumulate rather
   * than replace, which is why `nested-styles` in the fixture reads correctly
   * and why nothing caught this: only a span that *overrides* what it sits
   * inside can tell the two orders apart, and colour is the only such property.
   *
   * Pinned here rather than left uncovered so the divergence is a measured fact
   * with the reference's own answer beside it, and so the day someone closes it
   * this test fails and says what to do about it: move an overriding-colour
   * nesting into the corpus and regenerate (rich-markup-krk).
   */
  it("loses a nested colour override, where Rich repaints the inner run", () => {
    // Generated by the header's command with this string added to CASES.
    expect(printed("[red]a[blue]b[/blue]c[/red]")).toBe("\x1b[31mabc\x1b[0m");
    const reference = "\x1b[31ma\x1b[0m\x1b[34mb\x1b[0m\x1b[31mc\x1b[0m";
    expect(printed("[red]a[blue]b[/blue]c[/red]")).not.toBe(reference);
  });

  /*
   * The second: a span carrying both an attribute and a colour emits its SGR
   * parameters in the opposite order from the reference. The rendered result is
   * identical in any terminal — SGR parameters are a set — but the bytes are
   * not, and every byte-level fixture in this repository has to route around it.
   *
   * It is not a markup fact at all; the grammar has already finished by the time
   * a style is emitted. It is pinned in this file because it is the reason
   * `nested-styles` above nests attributes instead of the obvious `[bold red]`,
   * and a constraint on a fixture with no visible cause is how a corpus quietly
   * stops covering what it claims to (rich-color-7kv).
   */
  it("emits a combined style's SGR parameters colour-first, where Rich emits attribute-first", () => {
    // Generated by the header's command with this string added to CASES.
    expect(printed("[bold red]x[/]")).toBe("\x1b[31;1mx\x1b[0m");
    const reference = "\x1b[1;31mx\x1b[0m";
    expect(printed("[bold red]x[/]")).not.toBe(reference);
  });

  /*
   * The third divergence, and the only one that lives in `TAG_RE` itself.
   *
   * The reference's `RE_TAGS` captures the run of backslashes before the
   * bracket and halves it: each pair is one literal backslash, and a leftover
   * odd one escapes the tag. `\\[red]hi[/red]` therefore prints a single
   * backslash followed by styled text. This port's `TAG_RE` instead carries a
   * `\[` alternative that consumes any backslash-bracket pair as an escape, so
   * the opening tag is suppressed while `[/red]` is not, and the render dies on
   * a closing tag with nothing to match.
   *
   * The character class is what rich-markup-sec asked for and what the fixture
   * covers; the backslash arithmetic is a second, independent mechanism in the
   * same expression, and it is filed on its own (rich-markup-nm1).
   */
  it("cannot open a tag after an escaped backslash, where Rich halves the run", () => {
    // The reference prints "\\" followed by styled text — `\x1b[31mhi\x1b[0m`,
    // generated by the header's command with this string added to CASES. There
    // is no output to compare against, because this port reaches no output.
    expect(() => printed("\\\\[red]hi[/red]")).toThrow(MarkupError);
  });
});
