/*
 * How `RichText` breaks a line across a canvas, pinned against Python Rich.
 *
 * [LAW:one-source-of-truth] `text-wrap.golden.txt` is a committed copy of the
 * reference implementation's own output, not of this port's. Wrapping is the
 * one place in the library where text becomes lines — every renderable that
 * shows a string reaches it — and a golden generated by running this library
 * could only notice that the wrap changed, never that it was wrong. It was
 * wrong: for the life of this port `render` had no word-wrap step at all, so
 * `fold` chopped at fixed cell multiples and `crop` and `ellipsis` cut the
 * whole line, and a table cell wider than its column was truncated where the
 * reference wraps it (rich-table-6uy.7).
 *
 * Regenerating it therefore means re-deriving it from the reference, never
 * from this library — accepting whatever this library currently prints would
 * launder a regression into the fixture. Python Rich is not installable from
 * here (pypi is TLS-intercepted) but GitHub is, and it runs from a bare
 * checkout. This is the command the committed fixture came out of, verified to
 * reproduce it byte for byte; run it from the repository root:
 *
 *     git clone --depth 1 https://github.com/Textualize/rich.git /tmp/rich-src
 *     PYTHONPATH=/tmp/rich-src python3 - > test/core/text-wrap.golden.txt <<'PY'
 *     from rich.console import Console
 *     from rich.text import Text
 *     import sys
 *     TEXTS = [("sentence", "aaaa bbbb cccc dddd"),
 *              ("unbreakable", "aaaaaaaaaaaaaaaaaaaa"),
 *              ("pangram", "The quick brown fox jumps over the lazy dog"),
 *              ("long-word-mid", "The quick brownfoxjumpsoverthelazydogandmore end"),
 *              ("hanging-space", "aaaa      bbbb"),
 *              ("multiline", "one\ntwo three four five"),
 *              ("leading-space", "   indented words here"),
 *              ("trailing-space", "words then space   "),
 *              ("wide", "日本語のテキストです"),
 *              ("mixed-wide", "abc 日本語 def ghi"),
 *              ("single", "x")]
 *     WIDTHS = [1, 3, 5, 8, 20]
 *     OVERFLOWS = ["fold", "crop", "ellipsis"]
 *     console = Console(no_color=True, force_terminal=False, legacy_windows=False)
 *     blocks = []
 *     for name, value in TEXTS:
 *         for width in WIDTHS:
 *             for overflow in OVERFLOWS:
 *                 options = console.options.update(max_width=width, overflow=overflow)
 *                 rendered = "".join(
 *                     s.text for s in console.render(Text(value), options)
 *                 ).rstrip("\n")
 *                 blocks.append("%s w%d %s\n%s" % (name, width, overflow, rendered))
 *     sys.stdout.write("\n\n".join(blocks) + "\n")
 *     PY
 *
 * It goes through `console.render` with the overflow on the *options* rather
 * than through `console.print(Text(v, overflow=o))`, and the difference is not
 * cosmetic: `Console.print` rebuilds its arguments and drops a `Text`'s own
 * overflow, so the printed form silently renders every block as `fold`. A
 * fixture generated that way looks plausible — `fold` is a real answer — and
 * pins two of the three methods to the wrong one.
 *
 * WHY THIS CORPUS. Each text buys one arm of the wrap that no other buys.
 * `sentence` is the ticket's own case, the one a table cell hits. `unbreakable`
 * is its negative: a word no break can help, which must still meet the overflow
 * method, and it is what separates wrapping from "wrap everything". `pangram`
 * and `long-word-mid` put a too-long word among words that fit, which is the
 * only shape where `fold` and `crop` disagree about the *same* line.
 * `hanging-space` lands a break more than one space past the edge, the case
 * where trailing whitespace must be cropped without earning an ellipsis.
 * `multiline` proves the wrap is per logical line rather than per string.
 * `leading-space` and `trailing-space` pin whitespace at the two ends, which
 * the word regex treats asymmetrically. `wide` and `mixed-wide` are there
 * because every offset here is a cell offset and a two-cell glyph is where
 * cells and code units come apart. `single` is the degenerate one.
 *
 * The widths run down to 1 on purpose: a canvas of one cell cannot hold a
 * two-cell glyph, and the reference force-takes it rather than emitting an
 * empty line forever.
 *
 * Trailing spaces are significant — a wrap leaves the whitespace that preceded
 * it hanging on the line it closed, and several fixture lines end in it. Do not
 * trim the file.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { RichText } from "../../src/core/text.js";
import type { RenderOptions } from "../../src/core/protocol.js";

const GOLDEN = new URL("./text-wrap.golden.txt", import.meta.url);

const TEXTS: readonly (readonly [string, string])[] = [
  ["sentence", "aaaa bbbb cccc dddd"],
  ["unbreakable", "aaaaaaaaaaaaaaaaaaaa"],
  ["pangram", "The quick brown fox jumps over the lazy dog"],
  ["long-word-mid", "The quick brownfoxjumpsoverthelazydogandmore end"],
  ["hanging-space", "aaaa      bbbb"],
  ["multiline", "one\ntwo three four five"],
  ["leading-space", "   indented words here"],
  ["trailing-space", "words then space   "],
  ["wide", "日本語のテキストです"],
  ["mixed-wide", "abc 日本語 def ghi"],
  ["single", "x"],
];
const WIDTHS: readonly number[] = [1, 3, 5, 8, 20];
const OVERFLOWS: readonly RenderOptions["overflow"][] = ["fold", "crop", "ellipsis"];

function wrapped(value: string, maxWidth: number, overflow: RenderOptions["overflow"]): string {
  return [...new RichText(value).render({ maxWidth, overflow })]
    .map((segment) => segment.text)
    .join("")
    .replace(/\n+$/, "");
}

describe("RichText wrapping", () => {
  it("breaks lines where Python Rich breaks them", () => {
    const rendered =
      TEXTS.flatMap(([name, value]) =>
        WIDTHS.flatMap((width) =>
          OVERFLOWS.map(
            (overflow) => `${name} w${width} ${overflow}\n${wrapped(value, width, overflow)}`,
          ),
        ),
      ).join("\n\n") + "\n";

    expect(rendered).toBe(readFileSync(GOLDEN, "utf8"));
  });
});
