/*
 * The facts about `.github/` that used to be kept by hand: which major of each
 * action the workflows pin, where a workflow names its Node with a bare literal
 * instead of reading `package.json`, and that every job has a time limit.
 *
 * Hand-kept consistency across workflow files is how the epic this gate closes
 * (rich-workflows-0pr) began: three workflows gave three different Node
 * answers, and ci.yml carried a comment asserting that they could not drift.
 * rich-workflows-0pr.2 put checkout and setup-node on one major each and moved
 * every job that runs `src/` onto `node-version-file`. Nothing held either
 * change in place, and `.github/` was the one area of this repository with no
 * seam gate. actionlint checks syntax, not these conventions, and it is not
 * part of `npm run lint`.
 *
 * What the gate asserts:
 *
 *   - every remote action (`owner/repo`, any sub-path) is pinned to one major
 *     across every file under `.github/`. That includes `code-review.yml`, whose
 *     SHA pin carries its version as a `# vN.N.N` trailer, and the trailer is
 *     what gets read. That file is generated by the `agent-code-review-setup`
 *     skill and must not be edited by hand, but it is not exempt. When it
 *     disagrees, the fix is to align the hand-written workflows to it, or to
 *     change the skill's template and re-run the installer. An exempt file
 *     would be free to drift, and drift is what this gate exists to catch;
 *   - a bare `node-version:` appears only where `NODE_VERSION_LITERALS` grants
 *     it, one grant per occurrence, and a grant whose literal has gone is
 *     reported, so the list cannot collect permissions nobody needs;
 *   - every job in a workflow sets `timeout-minutes`. GitHub's default is six
 *     hours, and two PR #338 `ci` runs spent all of it stalled on an apt mirror
 *     inside the gate action's `playwright install --with-deps`
 *     (rich-workflows-1qvg). The bound sits on the job because a composite
 *     action's steps cannot carry one, and it is checked here because a new
 *     job, or a new caller of the gate action, inherits the default silently.
 *     Each bound is about twice the slowest healthy run, rounded up to ten
 *     minutes: on 2026-10-07 the `ci` job and publish's `gate` peaked at 10.6
 *     and 5.3 minutes and carry 20; every other job peaked under 1.5 and
 *     carries 10.
 *
 * [LAW:no-silent-failure] Regex over lines, not a YAML parser, and what makes
 * that sound is the catch-all. The dependency tree has no YAML parser, and
 * adding a devDependency to read two keys out of our own config costs more
 * than it buys, because the two keys have one conventional shape each. What
 * regex cannot do is recognise a shape nobody anticipated — a flow map
 * (`with: { node-version: 22 }`), a branch ref (`@main`), a SHA with no
 * trailer, a `docker://` image. So every non-comment line that mentions
 * either key and is not one of the recognised forms is reported as
 * unreadable. A new shape turns the gate red and names the line; it never
 * passes because the pattern missed it.
 *
 * Dependabot for the github-actions ecosystem was considered and not added.
 * It would redraw the version map automatically instead of asserting it stays
 * drawn, but it does that by opening pull requests on this repository
 * indefinitely, which changes behaviour people outside this code can see. That
 * is the owner's decision, not a side effect of a gate. The two do not
 * conflict: dependabot bumps each file in its own PR, and this gate would be
 * what keeps those PRs from landing half-done.
 *
 * THE BLIND SPOT, stated whenever this gate is cited: it checks that the
 * workflow files agree with each other. It cannot say whether the major they
 * agree on is the right one, whether an action still behaves as the comment
 * beside it claims, or whether a workflow runs at all. It trusts a SHA pin's
 * trailer without checking that the SHA is that version, which needs the
 * network. It checks that every job has a time limit, not that the limit
 * still fits the job. Only a real run answers those questions. The release path has had
 * real runs through the gate, the tag guard and provenance signing: 34924316777
 * (v0.9.0) and 34980189564 (v0.10.0), both stopped only at the registry.
 *
 * [LAW:effects-at-boundaries] Nothing here reads a file. The workflow texts
 * arrive as data from the test next door, so the verdict is a pure function of
 * (what the files say, what the table grants), and fixtures can supply files
 * this repository does not contain.
 */

/** One workflow file as the edge read it. */
export interface WorkflowText {
  /** Repo-relative path. */
  readonly path: string;
  readonly text: string;
}

/** Where a fact was found, quoted so a failure can be read without opening the file. */
export interface Site {
  readonly file: string;
  readonly line: number;
  readonly text: string;
}

/**
 * The lines of a workflow the gate has an opinion about.
 *
 * A local action (`./.github/actions/gate`) and `node-version-file:` produce
 * no fact: the first is versioned with this repository, the second is the
 * convention itself, and neither can disagree with anything.
 */
export type WorkflowFact =
  | { readonly kind: "pin"; readonly site: Site; readonly action: string; readonly major: number }
  | { readonly kind: "node-version"; readonly site: Site; readonly value: string }
  | { readonly kind: "job"; readonly site: Site; readonly name: string; readonly bounded: boolean }
  | { readonly kind: "unreadable"; readonly site: Site; readonly reason: string };

/**
 * A bare `node-version:` literal a workflow is allowed to carry.
 *
 * [LAW:one-source-of-truth] `why` is a summary, not the argument. The argument
 * is the comment above the literal in the workflow, because that is where the
 * next person to edit the workflow will read it. A grant is keyed on the value
 * as well as the file, so changing the literal fails the gate and makes someone
 * reread why it was allowed.
 */
export interface NodeVersionGrant {
  readonly file: string;
  readonly value: string;
  readonly why: string;
}

export const NODE_VERSION_LITERALS: readonly NodeVersionGrant[] = [
  {
    file: ".github/workflows/publish.yml",
    value: "22",
    why:
      "The publish job never runs `src/`; the tarball was compiled in the gate " +
      "job. Its Node exists to run npm 11, whose own `^20.17.0 || >=22.9.0` is " +
      "not a superset of `engines.node`, so reading the version file would " +
      "admit runtimes the job cannot use. The full argument is the comment " +
      "above the literal.",
  },
  {
    file: ".github/actions/node-floor/action.yml",
    value: "${{ steps.floor.outputs.version }}",
    why:
      "This step exists to run the lowest Node `engines.node` admits, and " +
      "`node-version-file` resolves that range to its newest version instead. " +
      "The value is computed from `engines.node` a step earlier, not typed. The " +
      "full argument is the comment above it.",
  },
];

export type WorkflowViolation =
  | { readonly rule: "unreadable"; readonly site: Site; readonly reason: string }
  | {
      readonly rule: "majors-disagree";
      readonly action: string;
      readonly pins: readonly { readonly major: number; readonly site: Site }[];
    }
  | {
      readonly rule: "node-version-count";
      readonly file: string;
      readonly value: string;
      readonly granted: number;
      readonly sites: readonly Site[];
    }
  | { readonly rule: "unbounded-job"; readonly site: Site; readonly name: string };

const COMMENT_LINE = /^\s*#/;
/**
 * Mentions either key anywhere on the line, the net under the recognised forms.
 * It is looser than `KEY_LINE` on purpose: a quoted key (`"uses":`) is valid
 * YAML that `KEY_LINE` does not read, and it must reach the unreadable report
 * rather than fall through the net and produce no fact at all.
 */
const MENTION = /\b(?:uses|node-version)["']?\s*:/;
/** A block-mapping key, optionally the first key of a sequence item. */
const KEY_LINE = /^\s*(?:-\s+)?(uses|node-version)\s*:\s*(.*)$/;
const TRAILER = /\s+#\s*(.*)$/;
const QUOTED = /^(["'])(.*)\1$/;
const REMOTE_ACTION = /^([\w.-]+\/[\w.-]+)(?:\/[^@\s]*)?@(\S+)$/;
const VERSION_TAG = /^v(\d+)(?:\.\d+){0,2}$/;
const COMMIT_SHA = /^[0-9a-f]{40}$/;

/**
 * A match's groups, read as the strings they must be.
 *
 * [LAW:no-silent-failure] Every group in this module's patterns is mandatory,
 * so a match missing one means the pattern is broken. That throws, instead of
 * reading as `""` and scanning on as if the line said nothing.
 */
function groupsOf(pattern: RegExp, text: string): ((index: number) => string) | null {
  const match = pattern.exec(text);
  return match === null
    ? null
    : (index) => {
        const group = match[index];
        if (group === undefined) throw new Error(`${pattern} matched without group ${index}`);
        return group;
      };
}

function unquote(value: string): string {
  return value.replace(QUOTED, "$2");
}

/** The action and major a `uses:` value pins, or why it cannot be read. */
function readPin(
  value: string,
  trailer: string,
): { action: string; major: number } | { reason: string } {
  const remote = groupsOf(REMOTE_ACTION, value);
  if (remote === null) {
    return { reason: `${JSON.stringify(value)} is neither owner/repo@ref nor ./local` };
  }
  // [LAW:dataflow-not-control-flow] A tag carries its version in the ref; a SHA
  // carries it in the trailer. Either way the version string ends up in one
  // place and is parsed by the same pattern.
  const ref = remote(2);
  const tag = groupsOf(VERSION_TAG, COMMIT_SHA.test(ref) ? trailer : ref);
  return tag === null
    ? {
        reason: COMMIT_SHA.test(ref)
          ? `SHA pin with no "# vN" trailer naming its version`
          : `ref ${JSON.stringify(ref)} names no major version`,
      }
    : // GitHub resolves owner/repo case-insensitively, so the identity does too.
      { action: remote(1).toLowerCase(), major: Number(tag(1)) };
}

const TOP_LEVEL = /^[^\s#]/;
const JOBS_MENTION = /^["']?jobs["']?\s*:/;
const JOBS_KEY = /^jobs:\s*(?:#.*)?$/;
/** A line indented exactly two spaces: inside `jobs:`, nothing but a job's id. */
const JOB_LEVEL = /^ {2}\S/;
const JOB_HEADER = /^ {2}([\w-]+):\s*(?:#.*)?$/;
const TIMEOUT_MENTION = /\btimeout-minutes["']?\s*:/;
/** A job's own key: four spaces, under the job header. */
const JOB_TIMEOUT = /^ {4}timeout-minutes:\s*\d+\s*(?:#.*)?$/;
/** A step's key, deeper than the job's. It bounds the step, not the job. */
const STEP_TIMEOUT = /^ {5,}timeout-minutes:\s*\d+\s*(?:#.*)?$/;

/**
 * Each job a workflow declares and whether it sets `timeout-minutes`.
 *
 * [LAW:no-silent-failure] Unlike the keys above, this needs to know which job a
 * line belongs to, so it walks with state: the `jobs:` block runs from that
 * top-level key to the next, and a job from its two-space header to the next.
 * The net is the same. Inside `jobs:`, a two-space line that is not a plain
 * `id:` header, a `jobs:` block with no header, and any `timeout-minutes` that
 * is neither a job's integer nor a step's is reported as unreadable, so a job
 * the patterns cannot see turns the gate red instead of escaping the rule. A
 * composite action has no `jobs:`, so any `timeout-minutes` in one is
 * unreadable too, which is the truth: GitHub ignores it there.
 */
function scanJobs(workflow: WorkflowText): WorkflowFact[] {
  const facts: WorkflowFact[] = [];
  let jobs: { site: Site; count: number } | null = null;
  let job: { site: Site; name: string; bounded: boolean } | null = null;
  const closeJob = () => {
    if (job !== null) facts.push({ kind: "job", ...job });
    job = null;
  };
  const closeJobs = () => {
    closeJob();
    if (jobs?.count === 0) {
      facts.push({ kind: "unreadable", site: jobs.site, reason: "a jobs: block with no job id this gate can read" });
    }
    jobs = null;
  };
  workflow.text.split(/\r?\n/).forEach((raw, index) => {
    if (COMMENT_LINE.test(raw)) return;
    const site: Site = { file: workflow.path, line: index + 1, text: raw.trim() };
    if (TOP_LEVEL.test(raw)) {
      closeJobs();
      if (JOBS_KEY.test(raw)) jobs = { site, count: 0 };
      else if (JOBS_MENTION.test(raw)) {
        facts.push({ kind: "unreadable", site, reason: "a jobs: key in a form this gate does not read" });
      }
      return;
    }
    if (jobs !== null && JOB_LEVEL.test(raw)) {
      closeJob();
      const header = groupsOf(JOB_HEADER, raw);
      if (header === null) {
        facts.push({ kind: "unreadable", site, reason: "a job id in a form this gate does not read" });
      } else {
        jobs.count += 1;
        job = { site, name: header(1), bounded: false };
      }
      return;
    }
    if (!TIMEOUT_MENTION.test(raw)) return;
    if (job !== null && JOB_TIMEOUT.test(raw)) job.bounded = true;
    else if (job === null || !STEP_TIMEOUT.test(raw)) {
      facts.push({ kind: "unreadable", site, reason: "a timeout-minutes this gate cannot place on a job or a step" });
    }
  });
  closeJobs();
  return facts;
}

/** Every fact one workflow file states: the keys in file order, then the jobs. */
export function scanWorkflow(workflow: WorkflowText): WorkflowFact[] {
  return [...scanKeys(workflow), ...scanJobs(workflow)];
}

function scanKeys(workflow: WorkflowText): WorkflowFact[] {
  return workflow.text.split(/\r?\n/).flatMap((raw, index): WorkflowFact[] => {
    if (COMMENT_LINE.test(raw) || !MENTION.test(raw)) return [];
    const site: Site = { file: workflow.path, line: index + 1, text: raw.trim() };
    const key = groupsOf(KEY_LINE, raw);
    if (key === null) {
      return [{ kind: "unreadable", site, reason: "mentions the key in a form this gate does not read" }];
    }
    // Split the value from a trailing `# comment`; with none, the trailer is empty.
    const [body = "", trailer = ""] = key(2).split(TRAILER);
    const value = unquote(body.trim());
    if (key(1) === "node-version") return [{ kind: "node-version", site, value }];
    if (value.startsWith("./")) return [];
    const pin = readPin(value, trailer.trim());
    return "major" in pin
      ? [{ kind: "pin", site, ...pin }]
      : [{ kind: "unreadable", site, reason: pin.reason }];
  });
}

function groupBy<T>(items: readonly T[], key: (item: T) => string): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const item of items) groups.set(key(item), [...(groups.get(key(item)) ?? []), item]);
  return groups;
}

/**
 * Every way `workflows` disagree with each other or with `grants`.
 *
 * [LAW:dataflow-not-control-flow] Every rule runs on every call. The
 * literal rule compares a count found with a count granted for every
 * (file, value) either side names: more found than granted is an
 * unsanctioned literal, fewer is a grant that outlived its literal, and both
 * are the same comparison.
 */
export function workflowViolations(
  workflows: readonly WorkflowText[],
  grants: readonly NodeVersionGrant[],
): WorkflowViolation[] {
  const facts = workflows.flatMap(scanWorkflow);

  const unreadable = facts.flatMap((f): WorkflowViolation[] =>
    f.kind === "unreadable" ? [{ rule: "unreadable", site: f.site, reason: f.reason }] : [],
  );

  const pins = facts.flatMap((f) => (f.kind === "pin" ? [f] : []));
  const disagreeing = [...groupBy(pins, (p) => p.action)]
    .filter(([, group]) => new Set(group.map((p) => p.major)).size > 1)
    .map(([action, group]): WorkflowViolation => ({
      rule: "majors-disagree",
      action,
      pins: group.map((p) => ({ major: p.major, site: p.site })),
    }));

  const literalKey = (file: string, value: string) => JSON.stringify([file, value]);
  const literals = groupBy(
    facts.flatMap((f) => (f.kind === "node-version" ? [f] : [])),
    (f) => literalKey(f.site.file, f.value),
  );
  const granted = groupBy(grants, (g) => literalKey(g.file, g.value));
  const miscounted = [...new Set([...literals.keys(), ...granted.keys()])].flatMap(
    (key): WorkflowViolation[] => {
      const [file, value] = JSON.parse(key) as [string, string];
      const sites = (literals.get(key) ?? []).map((f) => f.site);
      const count = granted.get(key)?.length ?? 0;
      return sites.length === count
        ? []
        : [{ rule: "node-version-count", file, value, granted: count, sites }];
    },
  );

  const unbounded = facts.flatMap((f): WorkflowViolation[] =>
    f.kind === "job" && !f.bounded ? [{ rule: "unbounded-job", site: f.site, name: f.name }] : [],
  );

  return [...unreadable, ...disagreeing, ...miscounted, ...unbounded];
}

function quote(site: Site): string {
  return `${site.file}:${site.line}  ${site.text}`;
}

/** A failure line naming the offence, every site involved, and the fix. */
export function describeWorkflowViolation(violation: WorkflowViolation): string {
  switch (violation.rule) {
    case "unreadable":
      return `  ${quote(violation.site)}\n      unreadable: ${violation.reason}`;
    case "majors-disagree":
      return (
        `  ${violation.action} is pinned to more than one major:\n` +
        violation.pins.map((p) => `      v${p.major}  ${quote(p.site)}`).join("\n")
      );
    case "node-version-count":
      return violation.sites.length > violation.granted
        ? `  ${violation.file}: ${violation.sites.length} bare node-version: ${violation.value}, ` +
            `NODE_VERSION_LITERALS grants ${violation.granted}\n` +
            violation.sites.map((s) => `      ${quote(s)}`).join("\n")
        : `  ${violation.file}: NODE_VERSION_LITERALS grants ${violation.granted} ` +
            `node-version: ${violation.value}, the workflow carries ${violation.sites.length} — ` +
            `drop the grant that outlived its literal.`;
    case "unbounded-job":
      return `  ${quote(violation.site)}\n      job ${violation.name} sets no timeout-minutes`;
  }
}
