/*
 * [LAW:verifiable-goals] rich-workflows-0pr.2 aligned the action majors and the
 * Node authority across every workflow by hand, and the one check it had was
 * someone reading all the files the same afternoon. This is that check in a
 * form the unit suite keeps.
 *
 * [LAW:behavior-not-structure] The assertion is the property a maintainer
 * relies on: the release path, the master path, and the docs deploy run the
 * same major of every action, and read Node from `engines` except where a
 * grant says why not. Reordering steps, splitting jobs, or adding a workflow
 * leaves it green as long as that property still holds.
 *
 * [LAW:effects-at-boundaries] The one read is here. `workflow-pins.ts` gets
 * the texts as data.
 */

import { describe, it, expect } from "vitest";
import path from "node:path";
import { readdirSync, readFileSync } from "node:fs";
import { REPO_ROOT } from "../coverage/extract.js";
import {
  NODE_VERSION_LITERALS,
  scanWorkflow,
  workflowViolations,
  describeWorkflowViolation,
  type WorkflowText,
} from "./workflow-pins.js";

/** Every YAML file under `.github/`: workflows and composite actions alike. */
function readWorkflows(): WorkflowText[] {
  const root = path.join(REPO_ROOT, ".github");
  return readdirSync(root, { recursive: true, encoding: "utf8" })
    .filter((entry) => /\.ya?ml$/.test(entry))
    .sort()
    .map((entry) => ({
      path: path.posix.join(".github", entry.split(path.sep).join("/")),
      text: readFileSync(path.join(root, entry), "utf8"),
    }));
}

const WORKFLOWS = readWorkflows();

describe("the workflows under .github/", () => {
  it("are all read, composite actions included", () => {
    // A walk that finds nothing leaves the gate below green for free.
    expect(WORKFLOWS.map((w) => w.path)).toEqual(
      expect.arrayContaining([
        ".github/actions/gate/action.yml",
        ".github/workflows/ci.yml",
        ".github/workflows/code-review.yml",
        ".github/workflows/deploy.yml",
        ".github/workflows/publish.yml",
      ]),
    );
  });

  it("pin one major per action and name Node only where a grant allows", () => {
    const failures = workflowViolations(WORKFLOWS, NODE_VERSION_LITERALS).map(
      describeWorkflowViolation,
    );
    expect(
      failures,
      `The workflows under .github/ have drifted apart. Move every pin of an ` +
        `action to one major in the same change. code-review.yml is generated by ` +
        `the agent-code-review-setup skill: align the other files to it, or change ` +
        `the skill's template and re-run its installer — never edit it by hand. A ` +
        `job that runs \`src/\` reads Node with \`node-version-file: package.json\`; ` +
        `any other bare literal needs a row in NODE_VERSION_LITERALS with its reason.` +
        `\n\n${failures.join("\n")}\n`,
    ).toEqual([]);
  });

  it("read the skill-authored workflow's SHA pins rather than skipping them", () => {
    const pins = WORKFLOWS.filter((w) => w.path === ".github/workflows/code-review.yml")
      .flatMap(scanWorkflow)
      .filter((f) => f.kind === "pin" && f.site.text.includes("# v"));
    expect(pins.length).toBeGreaterThan(0);
  });
});

describe("NODE_VERSION_LITERALS", () => {
  it("gives every grant a reason, and grants each literal once", () => {
    for (const grant of NODE_VERSION_LITERALS) {
      expect(grant.why.length, `${grant.file} ${grant.value} needs a why`).toBeGreaterThan(40);
    }
    const keys = NODE_VERSION_LITERALS.map((g) => `${g.file} ${g.value}`);
    expect(new Set(keys).size).toBe(keys.length);
  });
});

/**
 * The rules, pinned against files written to break them. The gate above is
 * green today, and a check nobody has seen go red is no evidence it can.
 */
function workflow(text: string, file = "wf.yml"): WorkflowText {
  return { path: file, text };
}

const GRANT = { file: "wf.yml", value: "22", why: "the fixture's reason" };

describe("workflowViolations: majors", () => {
  it("passes one action pinned to one major across files, patch levels aside", () => {
    expect(
      workflowViolations(
        [
          workflow("      - uses: actions/checkout@v7", "a.yml"),
          workflow("        uses: actions/checkout@v7.0.1", "b.yml"),
          workflow("      - uses: './.github/actions/gate'", "c.yml"),
        ],
        [],
      ),
    ).toEqual([]);
  });

  it("catches an action pinned to two majors, naming every site", () => {
    const [violation, ...rest] = workflowViolations(
      [
        workflow("      - uses: actions/checkout@v7", "a.yml"),
        workflow("steps:\n      - uses: actions/checkout@v6", "b.yml"),
      ],
      [],
    );
    expect(rest).toEqual([]);
    expect(violation).toEqual({
      rule: "majors-disagree",
      action: "actions/checkout",
      pins: [
        { major: 7, site: { file: "a.yml", line: 1, text: "- uses: actions/checkout@v7" } },
        { major: 6, site: { file: "b.yml", line: 2, text: "- uses: actions/checkout@v6" } },
      ],
    });
  });

  it("reads a SHA pin's major from its trailer", () => {
    const sha = "3d3c42e5aac5ba805825da76410c181273ba90b1";
    expect(
      workflowViolations(
        [workflow(`        uses: actions/checkout@${sha} # v6.0.0\n      - uses: actions/checkout@v7`)],
        [],
      )[0],
    ).toMatchObject({ rule: "majors-disagree", action: "actions/checkout" });
  });

  it("treats sub-paths of one repository as one action, whatever the case", () => {
    expect(
      workflowViolations(
        [workflow("- uses: github/codeql-action/init@v3\n- uses: GitHub/CodeQL-Action/analyze@v4")],
        [],
      )[0],
    ).toMatchObject({ rule: "majors-disagree", action: "github/codeql-action" });
  });

  it("ignores the keys where they appear in comments", () => {
    expect(
      workflowViolations(
        [workflow("  # the `uses:` line and a `node-version: 20` this replaced\n  # uses: x@main")],
        [],
      ),
    ).toEqual([]);
  });

  it.each([
    ["a SHA with no trailer", "- uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"],
    ["a branch ref", "- uses: actions/checkout@main"],
    ["a docker image", "- uses: docker://alpine:3.20"],
    ["a flow mapping", "  with: { node-version: 22 }"],
  ])("reports %s as unreadable rather than passing it", (_, line) => {
    expect(workflowViolations([workflow(line)], [])).toEqual([
      expect.objectContaining({ rule: "unreadable" }),
    ]);
  });
});

describe("workflowViolations: node-version literals", () => {
  it("passes the version file and a granted literal, quoted or not", () => {
    expect(
      workflowViolations(
        [workflow("          node-version-file: package.json\n          node-version: \"22\"")],
        [GRANT],
      ),
    ).toEqual([]);
    expect(workflowViolations([workflow("  node-version: 22 # npm 11")], [GRANT])).toEqual([]);
  });

  it("catches a literal with no grant", () => {
    expect(workflowViolations([workflow("          node-version: 20")], [])).toEqual([
      {
        rule: "node-version-count",
        file: "wf.yml",
        value: "20",
        granted: 0,
        sites: [{ file: "wf.yml", line: 1, text: "node-version: 20" }],
      },
    ]);
  });

  it("catches a second copy of a literal riding on one grant", () => {
    expect(
      workflowViolations([workflow("  node-version: 22\n  node-version: 22")], [GRANT]),
    ).toEqual([expect.objectContaining({ rule: "node-version-count", granted: 1, sites: expect.any(Array) })]);
  });

  it("catches a grant whose literal is gone", () => {
    expect(workflowViolations([workflow("  node-version-file: package.json")], [GRANT])).toEqual([
      { rule: "node-version-count", file: "wf.yml", value: "22", granted: 1, sites: [] },
    ]);
  });

  it("reports a changed literal as both unsanctioned and a stale grant", () => {
    const rules = workflowViolations([workflow("  node-version: 24")], [GRANT]).map((v) =>
      v.rule === "node-version-count" ? `${v.value}:${v.sites.length}/${v.granted}` : v.rule,
    );
    expect(rules.sort()).toEqual(["22:0/1", "24:1/0"]);
  });
});
