/*
 * The rendered frame of every shipped box style, pinned against Python Rich.
 *
 * [LAW:one-source-of-truth] `table-frames.golden.txt` is a committed copy of
 * the reference implementation's own output, not of this port's. That is the
 * whole point: a golden generated by running this library can only notice that
 * a frame changed, never that it was wrong to begin with — the expectation and
 * the subject would be the same code. Generated from Python Rich, the fixture
 * is an independent oracle, and it catches both defect classes this epic was
 * opened for: a table reaching for the wrong line of the grid (.1 and .2 of
 * rich-table-6uy), and a constant whose grid disagrees with it (.3).
 *
 * Regenerating it therefore means re-deriving it from the reference, never
 * from this library — accepting whatever this library currently prints would
 * launder a regression into the fixture. Python Rich is not installable from
 * here (pypi is TLS-intercepted) but GitHub is, and it runs from a bare
 * checkout. This is the command the committed fixture came out of, verified to
 * reproduce it byte for byte; run it from the repository root:
 *
 *     git clone --depth 1 https://github.com/Textualize/rich.git /tmp/rich-src
 *     PYTHONPATH=/tmp/rich-src python3 - \
 *       > test/renderables/table-frames.golden.txt <<'PY'
 *     from rich.console import Console
 *     from rich.table import Table
 *     import rich.box as box, sys
 *     NAMES = sorted(n for n, v in vars(box).items() if isinstance(v, box.Box))
 *     CONFIGS = [("header-footer-lines",
 *                 dict(show_header=True, show_footer=True, show_lines=True)),
 *                ("header-only",
 *                 dict(show_header=True, show_footer=False, show_lines=False)),
 *                ("no-header-no-footer",
 *                 dict(show_header=False, show_footer=False, show_lines=False))]
 *     blocks = []
 *     for name in NAMES:
 *         for label, opts in CONFIGS:
 *             c = Console(width=40, no_color=True, force_terminal=False,
 *                         legacy_windows=False)
 *             t = Table(box=getattr(box, name), **opts)
 *             t.add_column("A", footer="F"); t.add_column("B", footer="G")
 *             t.add_row("1", "2"); t.add_row("3", "4")
 *             with c.capture() as cap: c.print(t)
 *             blocks.append(name + " " + label + "\n" + cap.get().rstrip("\n"))
 *     sys.stdout.write("\n\n".join(blocks) + "\n")
 *     PY
 *
 * It mirrors the sweep below line for line — same columns, same rows, same
 * options, the constants enumerated off the reference's own module rather than
 * a hand-kept list, so the two lists cannot drift apart.
 *
 * WHY THIS CONFIGURATION. `header-footer-lines` is the only shape that draws
 * all eight lines of the grid: a header, two body rows, a separator between
 * them, a footer separator and a footer. Anything less leaves three lines
 * undrawn, which is precisely how three missing separator sets survived in
 * `Box` unnoticed until .3. `header-only` is the shape a caller gets by
 * default, and it is here so that skipping the footer block cannot start
 * drawing rows that should not appear.
 *
 * The footers are one character wide on purpose: a footer wider than its
 * column is truncated instead of widening the column (rich-table-css), and a
 * fixture built with wider ones would pin that defect and have to be redrawn
 * when it is fixed. The cells are plain digits for the same reason — table
 * cells render markup literally (rich-table-6uy.5).
 *
 * `no-header-no-footer` is the third because the reference swaps the box itself
 * when a table has no header — five of the nineteen constants map to a plainer
 * kin, the default HEAVY_HEAD among them (`Box.plainHeaded`). It is the only
 * configuration whose expected frames belong to a *different* constant than the
 * one named on the block, so it is the only one that catches the table drawing
 * with the box it was handed instead of the box it should have swapped to.
 *
 * Trailing spaces are significant: MINIMAL, SIMPLE and HORIZONTALS draw blank
 * corners, so several fixture lines end in whitespace and one is nothing but
 * whitespace. Every line is exactly nine cells wide. Do not trim the file.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import * as box from "../../src/core/box.js";
import { Segment } from "../../src/core/segment.js";
import { Table, type TableOptions } from "../../src/renderables/table.js";

const GOLDEN = new URL("./table-frames.golden.txt", import.meta.url);

// [LAW:one-source-of-truth] The module is the list of shipped styles. A
// twentieth constant joins the sweep by existing, and goes red until someone
// derives its frames from the reference.
const SHIPPED = Object.entries(box)
  .filter((entry): entry is [string, box.Box] => entry[1] instanceof box.Box)
  .sort(([a], [b]) => (a < b ? -1 : 1));

// [LAW:dataflow-not-control-flow] Which rows a frame contains is a value the
// one builder below takes, not a second builder.
const CONFIGURATIONS: readonly (readonly [string, TableOptions])[] = [
  ["header-footer-lines", { showHeader: true, showFooter: true, showLines: true }],
  ["header-only", { showHeader: true, showFooter: false, showLines: false }],
  ["no-header-no-footer", { showHeader: false, showFooter: false, showLines: false }],
];

function frame(style: box.Box, options: TableOptions): string {
  const table = new Table({ ...options, box: style });
  table.addColumn("A", { footer: "F" });
  table.addColumn("B", { footer: "G" });
  table.addRow("1", "2");
  table.addRow("3", "4");
  return Segment.splitLines([...table.render({ maxWidth: 40 })])
    .map((line) => line.map((segment) => segment.text).join(""))
    .join("\n");
}

describe("shipped box styles", () => {
  it("draw the frames Python Rich draws", () => {
    const rendered = SHIPPED.flatMap(([name, style]) =>
      CONFIGURATIONS.map(([label, options]) => `${name} ${label}\n${frame(style, options)}`),
    ).join("\n\n") + "\n";

    expect(rendered).toBe(readFileSync(GOLDEN, "utf8"));
  });
});
